set nocompatible               " be iMproved
filetype off                   " required!

" 
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle
" required! 
Bundle 'gmarik/vundle'

" My bundles are here
"
" Original repos on github
Bundle 'Valloric/YouCompleteMe'
Bundle 'scrooloose/syntastic'
Bundle 'majutsushi/tagbar'
Bundle 'nathanaelkane/vim-indent-guides'

" required!
syntax on
filetype indent plugin on

" Settings for python dev. Need to check if these are still
"   good for c,c++,etc ...
set softtabstop=2
set tabstop=8
set shiftwidth=2


